general = {
    output_backend = "pipe";
    ignore_volume_control = "yes";
};

pipe = {
    name = "/shared/audio";
    output_rate = "auto";
    output_format = "auto";
};

metadata = {
    pipe_name = "/shared/metadata";
};
